### ISSUE TITLE
'UnicodeDecodeError' for preprocessing

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/nea#1]
```
python3 preprocess_asap.py -i training_set_rel3.tsv
```
```
Traceback (most recent call last):
  File "preprocess_asap.py", line 44, in <module>
    dataset = collect_dataset(args.input_file)
  File "preprocess_asap.py", line 34, in collect_dataset
    for line in f:
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1539: invalid start byte
```

**Comment by ys7yoo** [comment]
https://github.com/nusnlp/nea/issues/11

**Comment by ys7yoo** [comment]
I'm gonna re-fork from https://github.com/tim-hub/nea.git

```
git remote add upstream https://github.com/tim-hub/nea.git
git fetch upstream
git rebase upstream/master
git push
```
