### ISSUE TITLE
replacing `keras.layers.embeddings`

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/nea#2]
```
[INFO] (nea.asap_reader)   443259 total words, 12118 unique words
[INFO] (nea.asap_reader)   Vocab size: 4000
[INFO] (nea.asap_reader) Reading dataset from: data/fold_0/train.tsv
[INFO] (nea.asap_reader)   <num> hit rate: 0.00%, <unk> hit rate: 2.19%
[INFO] (nea.asap_reader) Reading dataset from: data/fold_0/dev.tsv
[INFO] (nea.asap_reader)   <num> hit rate: 0.00%, <unk> hit rate: 2.81%
[INFO] (nea.asap_reader) Reading dataset from: data/fold_0/test.tsv
[INFO] (nea.asap_reader)   <num> hit rate: 0.00%, <unk> hit rate: 2.83%
[INFO] (__main__) Statistics:
[INFO] (__main__)   train_x shape: (1069, 939)
[INFO] (__main__)   dev_x shape:   (355, 886)
[INFO] (__main__)   test_x shape:  (356, 867)
[INFO] (__main__)   train_y shape: (1069,)
[INFO] (__main__)   dev_y shape:   (355,)
[INFO] (__main__)   test_y shape:  (356,)
[INFO] (__main__)   train_y mean: 8.551918, stdev: 1.5373031, MFC: [8.0]
Traceback (most recent call last):
  File "train_nea.py", line 160, in <module>
    model = create_model(args, train_y.mean(axis=0), overal_maxlen, vocab)
  File "/home/yyoo/src/nea/nea/models.py", line 9, in create_model
    from tensorflow.keras.layers.embeddings import Embedding
ModuleNotFoundError: No module named 'tensorflow.keras.layers.embeddings'
```

**Comment by ys7yoo** [comment]
replaced 
```
from tensorflow.keras.layers.embeddings import Embedding
```
with
```
from tensorflow.keras.layers import Embedding
```
