### ISSUE TITLE
replacing `keras.layers.core`

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/nea#3]
```
Traceback (most recent call last):
  File "/home/yyoo/src_remote/nea/train_nea.py", line 160, in <module>
    model = create_model(args, train_y.mean(axis=0), overal_maxlen, vocab)
  File "/home/yyoo/src_remote/nea/nea/models.py", line 11, in create_model
    from tensorflow.keras.layers.core import Dense, Dropout, Activation
ModuleNotFoundError: No module named 'tensorflow.keras.layers.core'
```

**Comment by ys7yoo** [comment]
replaced
```
from tensorflow.keras.layers.core import Dense, Dropout, Activation
```
with
```
from tensorflow.keras.layers import Dense, Dropout, Activation
```
