### ISSUE TITLE
replacing `keras.engine`

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/nea#4]
```
Traceback (most recent call last):
  File "/home/yyoo/src_remote/nea/train_nea.py", line 160, in <module>
    model = create_model(args, train_y.mean(axis=0), overal_maxlen, vocab)
  File "/home/yyoo/src_remote/nea/nea/models.py", line 12, in create_model
    from nea.my_layers import Attention, MeanOverTime, Conv1DWithMasking
  File "/home/yyoo/src_remote/nea/nea/my_layers.py", line 2, in <module>
    from tensorflow.keras.engine.topology import Layer
ModuleNotFoundError: No module named 'tensorflow.keras.engine'
```

**Comment by ys7yoo** [comment]
https://stackoverflow.com/questions/51337558/how-to-import-keras-engine-topology-in-tensorflow/51337967

**Comment by ys7yoo** [comment]
`keras.engine.topology.Layer()` Examples
https://www.programcreek.com/python/example/88972/keras.engine.topology.Layer

**Comment by ys7yoo** [comment]
https://stackoverflow.com/questions/49910880/convert-keras-engine-layer-to-tensorflow

**Comment by ys7yoo** [comment]
replaced 
```
from tensorflow.keras.engine.topology import Layer
```
with
```
from tensorflow.keras.layers import Layer
```
