### ISSUE TITLE
numpy.AxisError: axis 1 is out of bounds for array of dimension 1

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/nea#5]
```
Traceback (most recent call last):
  File "/home/yyoo/src_remote/nea/train_nea.py", line 160, in <module>
    model = create_model(args, train_y.mean(axis=0), overal_maxlen, vocab)
  File "/home/yyoo/src_remote/nea/nea/models.py", line 33, in create_model
    initial_mean_value = np.expand_dims(initial_mean_value, axis=1)
  File "<__array_function__ internals>", line 6, in expand_dims
  File "/home/yyoo/tf2/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 597, in expand_dims
    axis = normalize_axis_tuple(axis, out_ndim)
  File "/home/yyoo/tf2/lib/python3.6/site-packages/numpy/core/numeric.py", line 1358, in normalize_axis_tuple
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
  File "/home/yyoo/tf2/lib/python3.6/site-packages/numpy/core/numeric.py", line 1358, in <listcomp>
    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
```

**Comment by Jacksonvillor** [comment]
how to deal with this problem ??
