### ISSUE TITLE
Adding dropout to LSTM

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/nea#6]
```
Traceback (most recent call last):
  File "/home/yyoo/tf2/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 517, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/yyoo/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 340, in __init__
    generic_utils.validate_kwargs(kwargs, allowed_kwargs)
  File "/home/yyoo/tf2/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 808, in validate_kwargs
    raise TypeError(error_message, kwarg)
TypeError: ('Keyword argument not understood:', 'dropout_W')
python-BaseException
```

**Comment by ys7yoo** [comment]
https://stackoverflow.com/questions/55391226/typeerror-keyword-argument-not-understood-dropout

**Comment by ys7yoo** [comment]
Keras API: 
https://faroit.com/keras-docs/1.2.1/layers/recurrent/
* dropout_W: float between 0 and 1. Fraction of the input units to drop for input gates.
* dropout_U: float between 0 and 1. Fraction of the input units to drop for recurrent connections.

TF Keras API:
https://www.tensorflow.org/api_docs/python/tf/keras/layers/LSTM
* dropout: Float between 0 and 1. Fraction of the units to drop for the linear transformation of the inputs. Default: 0.
* recurrent_dropout: Float between 0 and 1. Fraction of the units to drop for the linear transformation of the recurrent state. Default: 0.
