### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'sum'

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/nea#7]
```
Traceback (most recent call last):
  File "/home/yyoo/src_remote/nea/train_nea.py", line 160, in <module>
    model = create_model(args, train_y.mean(axis=0), overal_maxlen, vocab)
  File "/home/yyoo/src_remote/nea/nea/models.py", line 68, in create_model
    model.add(MeanOverTime(mask_zero=True))
  File "/home/yyoo/tf2/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 517, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/yyoo/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/sequential.py", line 223, in add
    output_tensor = layer(self.outputs[0])
  File "/home/yyoo/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 952, in __call__
    input_list)
  File "/home/yyoo/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1091, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/home/yyoo/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/yyoo/tf2/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/yyoo/tf2/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 670, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    /home/yyoo/src_remote/nea/nea/my_layers.py:60 call  *
        return K.cast(x.sum(axis=1) / mask.sum(axis=1, keepdims=True), K.floatx())

    AttributeError: 'Tensor' object has no attribute 'sum'
```

**Comment by ys7yoo** [comment]
mean over time?
https://github.com/keras-team/keras/issues/2728

**Comment by AmyW-jh** [comment]
Have you solved this problem? How do you deal with it?
