### ISSUE TITLE
Adding CNN?

### ISSUE THREAD

**Issue by ys7yoo** [ys7yoo/nea#9]
```
Traceback (most recent call last):
  File "train_nea.py", line 160, in <module>
    model = create_model(args, train_y.mean(axis=0), overal_maxlen, vocab)
  File "/home/yyoo/src_remote/nea/nea/models.py", line 62, in create_model
    model.add(Conv1DWithMasking(nb_filter=args.cnn_dim, filter_length=args.cnn_window_size, border_mode=cnn_border_mode, subsample_length=1))
  File "/home/yyoo/src_remote/nea/nea/my_layers.py", line 84, in __init__
    super(Conv1DWithMasking, self).__init__(**kwargs)
TypeError: __init__() missing 2 required positional arguments: 'filters' and 'kernel_size'
```

**Comment by ys7yoo** [comment]
Keras API
https://faroit.com/keras-docs/1.2.2/layers/convolutional/

TF Keras API
https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv1D
